import type { LucideProps } from "lucide-react";
import {
  Activity, AlertTriangle, Archive, BarChart, BarChart2, Bell, Bookmark,
  Box, Boxes, Brain, Building2, Calculator, Calendar, CalendarCheck, CalendarDays, Car,
  CheckCircle2, ClipboardCheck, ClipboardList, Clock, Clock3, Database,
  Eye, FileClock, FileCheck2, FileText, Flag, Folder, GanttChart, Gauge, Globe, HelpCircle,
  History, Home, Image, Info, Layers, LayoutDashboard, LayoutGrid, List, Lock,
  Mail, Map, MapPin, Navigation, Package, Package2, PackageSearch, Phone,
  PieChart, Receipt, Route, Ruler, Scale, Search, Settings, Share2,
  ShieldAlert, ShieldCheck, Star, Tag, TicketIcon, Train, TrendingUp,
  Truck, Users, Warehouse, Wrench, Zap, ClipboardSignature, FolderOpen,
  Forklift, Plane, Ship, Weight,
} from "lucide-react";

export type NavIconName = keyof typeof NAV_ICONS;

export const NAV_ICONS: Record<string, React.ComponentType<LucideProps>> = {
  Activity,
  AlertTriangle,
  Archive,
  BarChart,
  BarChart2,
  Bell,
  Bookmark,
  Box,
  Boxes,
  Brain,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Car,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  ClipboardSignature,
  Clock,
  Clock3,
  Database,
  Eye,
  FileCheck2,
  FileText,
  Flag,
  Folder,
  FolderOpen,
  Forklift,
  GanttChart,
  Gauge,
  Globe,
  HelpCircle,
  History,
  Home,
  Image,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Navigation,
  Package,
  Package2,
  PackageSearch,
  Phone,
  PieChart,
  Plane,
  Receipt,
  Route,
  Ruler,
  Scale,
  Search,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Star,
  Tag,
  TicketIcon,
  Train,
  TrendingUp,
  Truck,
  Users,
  Warehouse,
  Weight,
  Wrench,
  Zap,
};

export const NAV_ICON_NAMES = Object.keys(NAV_ICONS).sort();
